spring:
  jackson:
    time-zone: Asia/Seoul
    property-naming-strategy: SNAKE_CASE

  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      jdbc:
        time_zone: Asia/Seoul
      ddl-auto: update
jwt:
  header: Authorization
  prefix: Bearer
  accessExpiration: 3600
  refreshExpiration: 604800
  secretKey: ${JWT_SECRET_KEY}
  adminSecret: ${ADMIN_SECRET}
  basicSecret: ${BASIC_SECRET}

  logging:
    level:
      root: DEBUG

redis:
  host: localhost
  port: 6379